# faça um programa que leie algo pelo teclado e mostre na tela
# o seu tipo primitivo e todas as informações possiveis sobre ele
i = input('interaja ou não: ')
print('é alphanumerico?')
print(i.isalnum())
print('é alfabético?')
print(i.isalpha())
print('é numerico?')
print(i.isnumeric())
print('é caracter ASCII?')
print(i.isascii())
print('é apenas digitos númericos?')
print(i.isdigit())
print('é decimal?')
print(i.isdecimal())
print('é minusculo?')
print(i.islower())
print('é maiusculo?')
print(i.isupper())
print('é imprimível?')
print(i.isprintable())
print('é indentificador válido?')
print(i.isidentifier())
print('é espaço?')
print(i.isspace())
print('é Titulo?')
print(i.istitle())
