n = input('digite algo: ')
tipo = type(n)
# print('O tipo primitivo desse valor é:', type(n))
print('O tipo primitivo desse valor é: {}'.format(tipo))
print('Só tem espaço? {}'.format(n.isspace()))
print('É númerico? {}'.format(n.isnumeric()))
print('É alfabético? {}'.format(n.isalpha()))
print('É alfanúmerico? {}'.format(n.isalnum()))
print('Está em maiúscula?', n.isupper())
print('Está em minúscula?', n.islower())
print('Está capitalizada?', n.istitle())
